### ISSUE TITLE
How to compile/install

### ISSUE THREAD

**Issue by BouweCeunen** [amzn/amazon-s3-gst-plugin#4]
Hi, How do we compile/install this to be used as a gstreamer plugin? Thanks.

**Comment by loganek** [comment]
Hi @BouweCeunen 
I've updated the readme file by including the instructions for building and installing the project: https://github.com/amzn/amazon-s3-gst-plugin/commit/ac6c578a45417103fba61766cb8ea222241aa3b3
Please let me know if those instructions are clear.

**Comment by BouweCeunen** [comment]
Hi @loganek, much appreciated. Thanks!

**Comment by BouweCeunen** [comment]
Hi @loganek, after I installed the aws sdk and did a make and make install, the meson build command and ninja install command succeeded but I'm still facing issues. 

A `gst-inspect-1.0 s3sink` shows me following issue; No such element or plugin 's3sink'. It complained about not finding libaws-cpp-sdk-core.so, libaws-cpp-sdk-s3.so and  libaws-cpp-sdk-sts.so so I copied those, but it didn't help. Are there still some extra steps?

Thanks!

**Comment by loganek** [comment]
@BouweCeunen looks more like a problem with AWS SDK, not the GStreamer plugin itself. Could you post commands you used for building and installing the SDK? There are a few potential issues:
 * Are those missing `.so` files in the library's search path? (you can temporarily set it using `LD_LIBRARY_PATH` env variable).
*  It's also possible that those libraries didn't land into the cache of the runtime linker, so running `ldconfig` command might also solve your problem.  
* Other option is that dependencies of `.so` files couldn't be found; you can check it by running `ldd /path/to/libaws-cpp-sdk-core.so` and see if all the dependencies are resolved

**Comment by BouweCeunen** [comment]
@loganek ldconfig solved it! 🎉
